library(shiny)
library(tidyverse)
library(shinydashboard)
library(RColorBrewer)
library(tigris)
library(dplyr)
library(ggplot2)
library(leaflet)
library(plotly)
library(leaflet.providers)
library(htmltools)
data <- read.csv(file = './cleaned_data.csv')
options(tigris_use_cache = TRUE)
char_zips <- zctas(cb = TRUE, starts_with = c('100', '101', '102', '103', '104','110', '111', '112', '113', '114', '116'))
colnames(char_zips@data)[1]= 'Zipcode' 
char_zips <- geo_join(char_zips, data, 'GEOID10', 'zipcode', by = 'Zipcode', how = 'inner')
leaflet <- leaflet() %>% setView(lng = -74.0060, lat = 42.3601, zoom = 10)
#values <- reactiveValues()
#PctMedInc <- data %>% select(., 'Zipcode', 'Percent Population', 'density')
